version: '3.7'
services:
  db:
    image: mysql:8.0.26
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=phpdb1234
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    # env_file:
    #   - ./app/.env
    volumes:
      - ./app:/usr/src/app
    user: 1000:1000
  nginx:
    image: nginx:1.15.3-alpine
    restart: always
    volumes:
      - ./app:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - php
  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
     - '8080:80'
    environment:
      - PMA_HOST=db